name: Reusable flow to check for vulns in dependencies of a Node.js branch

on:
  workflow_call:
    inputs:
      nodejsStream:
        type: string
        default: 'main'
    secrets:
      NVD_API_KEY:
        required: true
  workflow_dispatch:
    inputs:
      nodejsStream:
        type: string
        default: 'main'


permissions:
  contents: read
  issues: write

jobs:
  check-vulns:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Installing pre-reqs
        working-directory: ./dep_checker
        run: pip install -r requirements.txt
      - name: Checkout node.js repo
        uses: actions/checkout@v3
        with:
          repository: nodejs/node
          path: node
          ref: ${{ inputs.nodejsStream }}
      - name: Run the check
        working-directory: ./dep_checker
        run: |
          (
            set -o pipefail
            python main.py --json-output --gh-token ${{ secrets.GITHUB_TOKEN }} --nvd-key=${{ secrets.NVD_API_KEY }} ../node ${{ inputs.nodejsStream }} 2>&1 | tee result.log
          )
      - name: build matrix
        id: set_matrix
        if: ${{ failure() }}
        working-directory: ./dep_checker
        run: |
          matrix=$(cat result.log | jq -c .)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  create-issues:
    needs: check-vulns
    if: ${{ always() }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.check-vulns.outputs.matrix) }}
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3
      - uses: dblock/create-a-github-issue@v3
        with:
          update_existing: false
          search_existing: open
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VULN_ID: ${{ matrix.vulnerabilities.id }}
          VULN_URL: ${{ matrix.vulnerabilities.url }}
          VULN_DEP_NAME: ${{ matrix.vulnerabilities.dependency }}
          VULN_DEP_VERSION: ${{ matrix.vulnerabilities.version }}
          NODEJS_STREAM: ${{ inputs.nodejsStream }}
          ACTION_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
